[versions]
fabric-loom = "1.13-SNAPSHOT"
minecraft = "1.21.11"
fabric-loader = "0.17.3"
fabric-api = "0.139.4+1.21.11"
lombok = "1.18.42"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }