[versions]
fabric-loom = "1.14-SNAPSHOT"
minecraft = "26.1-snapshot-1"
fabric-loader = "0.18.3"
fabric-api = "0.140.3+26.1"
lombok = "1.18.42"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }